from typing import Any, TypedDict, Union

from openai.types.chat.chat_completion_message import ChatCompletionMessage
from pydantic import BaseModel
from enum import Enum

Message = Union[  # noqa: UP007 -- One of these types does not support the `|` operator
    str,
    list[dict[str, Any]],
    ChatCompletionMessage,
    dict[str, Any],
    BaseModel,
    TypedDict,
]


class Role(str, Enum):
    """
    Enum representing the role of a message within a conversation or system interaction.

    Attributes:
        USER: Represents a message originating from the user.
        ASSISTANT: Represents a message generated by the assistant.
        SYSTEM: Represents a message that pertains to system-level notifications or actions.
        TOOL: Represents a message that is output from a specific tool or utility used by the system.
    """

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    TOOL = "tool"


def get_role_from_message(message: Message) -> Role | None:
    ## check if not basemodel or dict return none
    if not isinstance(message, (dict, BaseModel)):
        return None
    message_data = message.model_dump() if isinstance(message, BaseModel) else message
    return message_data.get("role", None)


def get_content_from_message(message: Message | None) -> str | None:
    if message is None:
        return ""
    if isinstance(message, str):
        return message
    elif isinstance(message, list):
        combined = ", ".join(
            [
                item.get("content", "")
                for item in message
                if isinstance(item, dict) and item.get("content") is not None
            ]
        )
        if combined:
            return combined
    message_data = message.model_dump() if isinstance(message, BaseModel) else message
    return message_data.get("content", None)
